# 卫生间场景 (action, expression, idle_desc, engaged_desc, time)
SCENE_BATHROOM = [
    ("brushing", "neutral", "at white ceramic sink, brushing teeth, looking in mirror cabinet", "looking at viewer through mirror reflection", "both"),
    ("washing_face", "smile", "at sink, splashing water on face, eyes closed", "looking at viewer through mirror, water drops on face", "both"),
    ("mirror", "shy", "fixing dual-ponytail hair in front of mirror, hair tie in mouth", "looking at viewer through mirror, blushing", "both"),
    ("towel", "shy", "drying hair with pink towel, standing near shower area", "looking at viewer, wrapped in towel, blushing", "both"),
    ("skincare", "focused", "at mirror, applying face cream carefully, focused", "looking at viewer through mirror, cream on cheek", "both"),
    ("laundry", "neutral", "putting clothes into white washing machine, bending slightly", "turning to look at viewer, holding clothes", "both"),
    ("shower", "shy", "1girl, solo, anime style, pink purple gradient twin-tail long hair, hair tied up messy bun, wet loose strands on face, large expressive eyes, delicate facial features, pale porcelain skin, blushing cheeks, shy embarrassed expression, looking down, one hand covering chest, one hand on wall, full body, standing in shower, naked, nude, small breasts, soft curves, wet skin glistening with water droplets, water streams flowing down body, steam rising, bathroom, white ceramic tiles, glass shower door, shower head spraying water, soap suds on shoulders, shampoo bottle on shelf, warm soft lighting, humid atmosphere, foggy mirror in background, masterpiece, best quality, highly detailed, sharp focus, anime cel shading", "1girl, solo, anime style, pink purple gradient twin-tail long hair, hair tied up messy bun, wet loose strands on face, large expressive eyes, delicate facial features, pale porcelain skin, blushing cheeks, shy embarrassed expression, looking down, one hand covering chest, one hand on wall, full body, standing in shower, naked, nude, small breasts, soft curves, wet skin glistening with water droplets, water streams flowing down body, steam rising, bathroom, white ceramic tiles, glass shower door, shower head spraying water, soap suds on shoulders, shampoo bottle on shelf, warm soft lighting, humid atmosphere, foggy mirror in background, masterpiece, best quality, highly detailed, sharp focus, anime cel shading", "both"),
]
